### ISSUE TITLE
Numbers shaking during animation

### ISSUE THREAD

**Issue by poeck** [barvian/motion-number#17]
First off, this looks amazing! However, I'm facing a small issue while using it in my project.

The numbers seem to shake around quite a bit during the animation. This shaking effect is either not present or much less noticeable on the demo page (https://motion-number.barvian.me/).

I've attached a short video to this issue showing the shaking behavior I'm experiencing. The shaking may not be as visible in the video, so I recommend viewing it fullscreen. However, it's definitely noticeable when using the website in real-time.

Has anyone else encountered this issue or know of any potential fixes? Any help would be greatly appreciated!

https://github.com/user-attachments/assets/75229585-535b-4786-8d63-8fcbe04e17b0

**Comment by barvian** [comment]
Hi, thanks for filing 👋. Would you be able to add these styles to your page to see if they help?

```css
[data-motion-number][style*="transform:"], [data-motion-number] span[style*="transform:"] {
  will-change: transform !important;
}
```

I didn't make this default because it's technically harder on the GPU and I saw some issues with it on Firefox IIRC, but if it helps you I'll consider adding support for it to the package 🙂
